
####### MySQL Data-Source Properties #######
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3307/aethenos_db?useSSL=false
#spring.datasource.username=exon_aethenos
#spring.datasource.password=@t8p0eA11
spring.datasource.username=root
spring.datasource.password=9922557gimna
spring.jpa.show-sql=true

jwt.secret=secret

######## Max File Size and Max Request Size #########
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

